# SIGNUP
POST http://localhost:3000/sign-up HTTP/1.1
content-type: application/json

{
    "pseudo": "romain15",
    "password": "romain",
    "email": "romain7@nicos.com"
}

###
# LOGIN
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "pseudo": "romain16",
    "password": "romain"
    
}
###
# LOGIN
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "pseudo": "romain7",
    "password": "romain",
    "email": "romain7@nicolas.com"
}
###

# GET USER
POST http://localhost:3000/user
content-type: application/json

{
    "token": "\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsInBzZXVkbyI6Im5pY29sYXNzIiwiZW1haWwiOiJybmljb2xhc0BuaWNvbGFzLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjY0NDg1MzE3LCJleHAiOjE2NjQ3NDQ1MTd9.hq_mQa8LZFL_wDISflmfYOnswV8AHufMvB-nrqS6-g4\""
}

###
PATCH http://localhost:3000/user
content-type: application/json

{
    "token": "\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInBzZXVkbyI6InJvbWFpbjE2IiwiZW1haWwiOiJyb21haW4zQGdhbWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjY0NTQ2Mzg5LCJleHAiOjE2NjQ4MDU1ODl9.GJXJ3hddbqKkIXgK4ozkQE-tVCwGg5czALI_B3oRehw\"",
    "pseudo": "romain16",
    "password": "romain",
    "email": "romain3@hotmail.com"
}
###

DELETE  http://localhost:3000/user
content-type: application/json

{
    "token": "\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsInBzZXVkbyI6InJvbWFpbiIsImVtYWlsIjoicm9tYWluQG5pY29sYXMuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjQ0ODg3ODQsImV4cCI6MTY2NDc0Nzk4NH0.X3osN74S6Z29TC20k_hRzq8KQ1ZQ5ed00YZqN3bhBHM\""
}
###
POST http://localhost:3000/users
content-type: application/json

{
    "token": "\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsInBzZXVkbyI6Im5pY29sYXNzIiwiZW1haWwiOiJybmljb2xhc0BuaWNvbGFzLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjY0NDg1MzE3LCJleHAiOjE2NjQ3NDQ1MTd9.hq_mQa8LZFL_wDISflmfYOnswV8AHufMvB-nrqS6-g4\""
}
###
