GET http://localhost:3000/user/2

###

POST http://localhost:3000/sign-up HTTP/1.1
content-type: application/json

{
    "pseudo": "hean",
    "password": "jean1",
    "email": "jean@jean.com"
}

###

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "pseudo": "hean",
    "password": "jean1"
}

###

GET http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "pseudo": "romain@romain.com",
    "password": "romain"
}