# SIGNUP
POST http://localhost:3000/sign-up HTTP/1.1
content-type: application/json

{
    "pseudo": "c",
    "password": "c",
    "email": "c@"
}

###
# SIGNUP
POST http://localhost:3000/sign-up HTTP/1.1
content-type: application/json

{
    "pseudo": "b",
    "password": "b",
    "email": "b@"
}

###
# LOGIN
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "pseudo": "a",
    "password": "a"
    
}
###
# LOGIN
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "pseudo": "romain7",
    "password": "romain",
    "email": "romain7@nicolas.com"
}
###

# GET USER
POST http://localhost:3000/user?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsInBzZXVkbyI6ImYiLCJlbWFpbCI6ImZAIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjUzODYyODYsImV4cCI6MTY2NTY0NTQ4Nn0.W39mfbOysyeEjnEiIb7PZdB9v8XepniO4InMTFQkjT4


###
PATCH http://localhost:3000/user?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsInBzZXVkbyI6ImYiLCJlbWFpbCI6ImZAIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjUzODU2NTQsImV4cCI6MTY2NTY0NDg1NH0.eiuvDmlbsbVAH_XT1cShKrahYqlKDqZNcJEoZFk46vE
content-type: application/json

{
    "content": {
                "password": "ee" 
    }
      
}
###

DELETE  http://localhost:3000/user
content-type: application/json

{
    "token": "\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsInBzZXVkbyI6InJvbWFpbiIsImVtYWlsIjoicm9tYWluQG5pY29sYXMuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjQ0ODg3ODQsImV4cCI6MTY2NDc0Nzk4NH0.X3osN74S6Z29TC20k_hRzq8KQ1ZQ5ed00YZqN3bhBHM\""
}
###
POST http://localhost:3000/users?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInBzZXVkbyI6ImEiLCJlbWFpbCI6ImFAIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY1NDAzNTkzLCJleHAiOjE2NjU2NjI3OTN9.TK9GENe_9iw0xiLxxP3iTssIjz37PflkgCdjpfkQEwY

###
POST http://localhost:3000/users?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsInBzZXVkbyI6ImIiLCJlbWFpbCI6ImJAIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjU0MDM3NDcsImV4cCI6MTY2NTY2Mjk0N30.Mdyyp843hMfr2081VlrbLqdpIocebVw2HZCWg8ZA51A

###

###
POST http://localhost:3000/user?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsInBzZXVkbyI6ImUiLCJlbWFpbCI6ImVAIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjUxNDQ2OTIsImV4cCI6MTY2NTQwMzg5Mn0.NF2BDs6oG1BRDcPh7dwLtXrA3yw99L1ZWrYJyahaapo
